name: braindecode
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
- python>=3.7
- numpy
- pandas
- scipy
- mkl
- matplotlib
- h5py
- pytest
- pytorch
- pip
- skorch
- pip:
  - mne
  - https://github.com/braindecode/braindecode/zipball/master
  #- torch # for now via pip as long as conda version causes problems on CPU
