name: braindecode
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
- python>=3.7
- numpy
- pandas
- scipy
- mkl
- matplotlib
- h5py
- pytorch
- pytest
- pip
- skorch
- joblib
- pip:
  - git+https://github.com/mne-tools/mne-python.git@5cc6eb8d7ebd102049843336d9d4a342f0f3e966
  - https://github.com/braindecode/braindecode/zipball/master
