# Tagging a commit with [circle front] will build the front page and perform test-doc.
# Tagging a commit with [circle full] will build everything.
version: 2
jobs:
    fetch_docs_from_github:
      docker:
        - image: circleci/python:3.7-stretch
      steps:
        - run:
            name: Download some docs
            command: |
              wget -O HTML-docs.zip https://nightly.link/braindecode/braindecode/actions/artifacts/53832858.zip
              ls -ahl .
              unzip HTML-docs.zip -d downloaded_docs
              ls -ahl .
        # Save the outputs
        - store_artifacts:
           path: downloaded_docs/html/
           destination: dev
        - persist_to_workspace:
           root: downloaded_docs
           paths:
             - html

workflows:
  version: 2

  default:
    jobs:
      - fetch_docs_from_github
