# Tagging a commit with [circle front] will build the front page and perform test-doc.
# Tagging a commit with [circle full] will build everything.
version: 2.1
parameters:
  github-artifact-url:
    type: string
    default: "latest"
jobs:
    fetch_docs_from_github:
      docker:
        - image: circleci/python:3.7-stretch
      environment:
        GITHUB_ARTIFACT_URL: << pipeline.parameters.github-artifact-url >>
      steps:
        - run:
            name: Download some docs
            command: |
              echo "Show Github artifact url"
              echo $GITHUB_ARTIFACT_URL
              wget -O HTML-docs.zip $GITHUB_ARTIFACT_URL
              ls -ahl .
              unzip HTML-docs.zip -d downloaded_docs
              ls -ahl .
        # Save the outputs
        - store_artifacts:
           path: downloaded_docs/html/
           destination: dev
        - persist_to_workspace:
           root: downloaded_docs
           paths:
             - html

workflows:
  version: 2

  default:
    jobs:
      - fetch_docs_from_github
