name: Installation of Braindecode
on: [push]
jobs:
  Install-Braindecode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: 3.7
        conda-channels: anaconda, conda-forge, pytorch
    - shell: bash -l {0}  
    - run: conda --version
    - run: conda env create -f environment.yml
    - run: conda init bash
    - run: source activate braindecode
    - run: conda info --envs
    - run: which python
    - run: python -c "import braindecode; print(braindecode.__version__)"
    # Install MOABB as well
    - run: pip install moabb
