name: Installation of Braindecode
on: [push]
jobs:
  Install-Braindecode:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        python-version: 3.7
        activate-environment: braindecode
        auto-activate-base: false
    - run: conda --version
    - run: conda info --envs
    - run: which $CONDA/bin/python
    - run: $CONDA/bin/python -c "import braindecode; print(braindecode.__version__)"
    - run: which python
    - run: python -c "import braindecode; print(braindecode.__version__)"
    # Install MOABB as well
    - run: $CONDA/bin/pip install moabb
    - run: $CONDA/bin/pip install -e .
