name: Install And Run Tests of Braindecode
on: [push]
jobs:
  Install-Test-Braindecode:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checking out repository 
      uses: actions/checkout@v2
    - name: Setting up conda braindecode environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        python-version: 3.7
        activate-environment: braindecode
        auto-activate-base: false
    # Show Conda Versions and Braindecode Versions
    - run: conda --version
    - run: conda info --envs
    - run: which python
    - run: python -c "import braindecode; print(braindecode.__version__)"
    # Install MOABB as well
    - name: Install MOABB
      run: pip install moabb
    - name: Install Braindecode from current checkout
      run: pip install -e .
    - name: Install codecov etc.
      run: pip install --upgrade pytest pytest-cov codecov
    - name: Run Tests
      run: pytest --cov=braindecode test/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - name: Install docs requirements
      run: python -m pip install --upgrade -r docs/requirements.txt
    - name: Install newer versions scikit learn scipy to prevent error # should be removed once moabb reason is clearer
      run: pip install --upgrade scipy scikit-learn
    - name: Create Docs
      run: |
        cd docs
        make html
    - name: Upload HTML Docs as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: HTML-Docs
        path: ./docs/_build/
