name: push-artifact-to-circle-ci

# will be changed to on workflow_run
on:
  workflow_run:
    workflows: ["tests-and-docs"]

jobs:
  Push-Artifact-to-CircleCI:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Try setting pull number #https://stackoverflow.com/a/60723400/1469195
      id: get-pr-number
      uses: actions/github-script@v4
      with:
        github-token: ${{github.token}}
        script: |
          const prNumber = context.payload.number;
          core.exportVariable('PULL_NUMBER', prNumber);
          return prNumber  
        result-encoding: string
    - name: Show some stuff
      env:
        PR_NUMBER: ${{ github.event.number }}
        EVENT_OBJ:  ${{ toJson(github.event) }}
        COMMIT_SHA:  ${{ github.event.workflow_run.head_sha }}
        REPO_NAME:  ${{ github.event.workflow_run.head_repository.full_name }}
      run: |
      
        echo "github.event.workflow_run.head_sha"
        echo ${{ github.event.workflow_run.head_sha }}
        echo "github.event.workflow_run.head_repository.html_url"
        echo ${{ github.event.workflow_run.head_repository.html_url }}
        echo "manual curl"
        curl -H "Accept: application/vnd.github.groot-preview+json"   https://api.github.com/repos/robintibor/braindecode-1/commits/d353344aa8dfebc395ae3b515419df22d6f652ff/pulls 2>/dev/null | jq '.[0].number' > cat pull_nr.txt
        #echo "automated curl"
        #curl -H "Accept: application/vnd.github.groot-preview+json"   https://api.github.com/repos/$REPO_NAME/commits/$COMMIT_SHA/pulls 2>/dev/null | jq '.[0].number' > cat pull_nr.txt
        cat pull_nr.txt
        echo "steps.set-result.outputs.result"
        echo "${{steps.set-result.outputs.result}}"
        echo "PULL_NUMBER"
        echo $PULL_NUMBER
        echo "EVENT_OBJ"
        echo $EVENT_OBJ
        echo "PR_NUMBER"
        echo $PR_NUMBER
        echo "Github REF"
        echo $GITHUB_REF
        echo "$GITHUB_EVENT_PATH"
        echo $GITHUB_EVENT_PATH
        curl --request POST \
          --url https://circleci.com/api/v2/project/gh/braindecode/braindecode/pipeline \
          --header 'Circle-Token: SECRETTOKEN' \
          --header 'content-type: application/json' \
          --header 'x-attribution-actor-id: github_actions' \
          --header 'x-attribution-login: github_actions' \
          --data '{"branch":"pull/209/head","parameters":{"github-artifact-url":"test"}}'
