name: push-artifact-to-circle-ci

# will be changed to on workflow_run
on:
  workflow_run:
    workflows: ["tests-and-docs"]

jobs:
  Push-Artifact-to-CircleCI:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Show some stuff
      env:
        EVENT_OBJ:  ${{ toJson(github.event) }}
        COMMIT_SHA:  ${{ github.event.workflow_run.head_sha }}
        REPO_NAME:  ${{ github.event.workflow_run.head_repository.full_name }}
      run: |
        echo "github.event.workflow_run.head_sha"
        echo ${{ github.event.workflow_run.head_sha }}
        echo "github.event.workflow_run.head_repository.html_url"
        echo ${{ github.event.workflow_run.head_repository.html_url }}
        echo "manual curl"
        PR_NUMBER=$(curl -H "Accept: application/vnd.github.groot-preview+json"   https://api.github.com/repos/robintibor/braindecode-1/commits/d353344aa8dfebc395ae3b515419df22d6f652ff/pulls 2>/dev/null | jq '.[0].number')
        #echo "automated curl"
        #curl -H "Accept: application/vnd.github.groot-preview+json"   https://api.github.com/repos/$REPO_NAME/commits/$COMMIT_SHA/pulls 2>/dev/null | jq '.[0].number'
        echo $PR_NUMBER
        curl --request POST \
          --url https://circleci.com/api/v2/project/gh/braindecode/braindecode/pipeline \
          --header 'Circle-Token: SECRETTOKEN' \
          --header 'content-type: application/json' \
          --header 'x-attribution-actor-id: github_actions' \
          --header 'x-attribution-login: github_actions' \
          --data '{"branch":"pull/209/head","parameters":{"github-artifact-url":"test"}}'
        echo "EVENT_OBJ"
        echo $EVENT_OBJ
