name: Tests using PyTest
on: [push]
jobs:
  Install-Braindecode:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repository 
      uses: actions/checkout@v2
    - name: Install braindecode
      uses: ./.github/workflows/install.yml
    - run: pip install --upgrade pytest pytest-cov codecov
    - run: pytest --cov=braindecode test/
